typedef enum CommandType {
	AND    ,
	OR     ,
	XOR    ,
	NOT    ,
	SHFTR  ,
	SHFTRI ,
	SHFTL  ,
	SHFTLI ,
	BR     ,
	BRR     ,     
	BRR2     ,
	BRNZ     ,
	CALL     ,
	RETURN     ,
	BRGT     ,
	PRIV     ,
	MOV     ,
	MOV1     ,
	MOV2     ,
	MOV3     ,
	ADDF     ,
	SUBF     ,
	MULF     ,
	DIVF     ,
	ADD     ,
	ADDI     ,
	SUB     ,
	SUBI     ,
	MUL     ,
	DIV     ,
// MACROS
	IN,
	OUT,
	CLR,
	LD,
	PUSH,
	POP,
// data
	DATA,
	HALT,
} CommandType;

typedef struct {
    const char *name;
	CommandType type;
	int cnt;
	int opcode;
} CmdMap;

static CmdMap cmdTable[] = {
    {"and", AND, 1, 0x0}, 
	{"or", OR, 1, 0x1}, 
	{"xor", XOR, 1, 0x2}, 
	{"not", NOT, 1, 0x3},
    {"shftr", SHFTR, 1, 0x4}, 
	{"shftri", SHFTRI, 1, 0x5},
    {"shftl", SHFTL, 1, 0x6},
	{"shftli", SHFTLI, 1, 0x7},
    {"br", BR, 1, 0x8},
	{"brr", BRR, 1, 0x9}, 
	{"brr", BRR2, 1, 0xa}, 
	{"brnz", BRNZ, 1, 0xb}, 
    {"call", CALL, 1, 0xc},
	{"return", RETURN, 1, 0xd},
	{"brgt", BRGT, 1, 0xe},
    {"priv", PRIV, 1, 0xf},
    {"mov", MOV, 1, 0x10},
    {"mov", MOV1, 1, 0x11},
    {"mov", MOV2, 1, 0x12},
    {"mov", MOV3, 1, 0x13},
    {"addf", ADDF, 1, 0x14}, 
	{"subf", SUBF, 1, 0x15},
    {"mulf", MULF, 1, 0x16}, 
	{"divf", DIVF, 1, 0x17},
    {"add", ADD, 1,   0x18}, 
	{"addi", ADDI, 1, 0x19},
    {"sub", SUB, 1,   0x1a}, 
	{"subi", SUBI, 1, 0x1b},
    {"mul", MUL, 1, 0x1c}, 
	{"div", DIV, 1, 0x1d},

    {"in", IN, 1, -1},
	{"out", OUT, 1, -1},
    {"clr", CLR, 1, -1}, 
	{"ld", LD, 12, -1},
    {"push", PUSH, 2, -1}, 
	{"pop", POP, 2, -1},
    {"data", DATA, 1, -1},
	{"halt", HALT, 1, -1}
};

